mtm:  
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100 

  # Torque Controllers ---------------------------------------
  joint1_torque_controller:
    type: effort_controllers/JointEffortController
    joint: right_outer_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_torque_controller:
    type: effort_controllers/JointEffortController
    joint: right_shoulder_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_torque_controller:
    type: effort_controllers/JointEffortController
    joint: right_elbow_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_torque_controller:
    type: effort_controllers/JointEffortController
    joint: right_wrist_platform_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_torque_controller:
    type: effort_controllers/JointEffortController
    joint: right_wrist_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint6_torque_controller:
    type: effort_controllers/JointEffortController
    joint: right_wrist_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint7_torque_controller:
    type: effort_controllers/JointEffortController
    joint: right_wrist_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

